### PR TITLE
feat(HMS-4532): mock pendo

### PR DESCRIPTION
**Pull request by avisiedo**
Quick mock service to mock pendo, to prepare
the repository to use it on smoke tests.

Depends on: https://github.com/podengo-project/idmsvc-backend/pull/292

https://issues.redhat.com/browse/HMS-4532

### CODE REVIEW

**Comment by pvoborni** [comment]
I don't think that we need mock like this atm as mocking the client or using dump might be good enough atm. But if we would like to use a mock service, why are we creating custom mock services and not using https://github.com/mock-server/mockserver that is already partly configured in our compose https://github.com/podengo-project/idmsvc-backend/blob/main/deployments/docker-compose.yaml#L7 . I think adding configuration to it might make the trick.

**Comment by avisiedo** [comment]
About mock-server; it is true it is partially configured. What I recall when I added, I needed more knowledge for using it; I was capable to set up a mock response with it, but I had some situation related with preparing additional responses and with the sequence. I would need to repeat and try to set-up the process with mock-server.

**Comment by frasertweedale** [comment]
Should we close this PR?  We can resurrect it later if we decide to resume the mock effort, using the same approach.

**Comment by avisiedo** [comment]
:+1: closed

**Pull request closed without merging**
