### PR TITLE
fix(HMS-3805): add mixed enforcement

### PR DESCRIPTION
**Pull request by avisiedo**
This change allow to define routes for mixed enforcement for the routes that could be reached out by users or systems.

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
I don't particularly like the current approach. Before we had two lookup tables and check functions. Now we have three. It's code duplication and three places to check if one wants to understand access permissions

I would rather do something like this:

```golang
type enforceRoute struct {
	Method string
	Path   string
	System bool
    User bool
}

and the define permissions like this:
```golang
{"GET", "/api/idmsvc/v1/domains/:uuid", true, true},
```

or maybe use a bit map:

```golang
USER_ACCESS = 1
SYSTEM_ACCESS = 2
ALL_ACCESS = USER_ACCESS | SYSTEM_ACCESS
```

```golang
type enforceRoute struct {
	Method string
	Path   string
	Access uint
}

{"GET", "/api/idmsvc/v1/domains/:uuid", ALL_ACCESS}

if route.Access & USER_ACCESS == USER_ACCESS { ... }
```

**Comment by avisiedo** [comment]
I agree some refactor is necessary, but it was not my intention to make that refactor on this PR. Thanks for the observation.

**Comment by frasertweedale** [comment]
Yeah I agree we can refactor later.  In fact, we already have a ticket that proposes a nicer way: https://issues.redhat.com/browse/HMS-2459 .

**Review by frasertweedale — APPROVED** [review]

**Comment by tiran** [comment]
I also noticed that the change gives a domain too much access. A domain should only be able to view its own data and not be able to access any other domain.

**Comment by frasertweedale** [comment]
> I also noticed that the change gives a domain too much access. A domain should only be able to view its own data and not be able to access any other domain.

The lookup filters by org ID, and therefore 404s if the requested domain exists in a different org.

For the middleware to enforce it, we would have to do the lookup in the middleware.  In any case, I don't think the current behaviour is wrong.  But if I am missing something please put me straight!

**Comment by frasertweedale** [comment]
There were no further comment or objections, so merging this now.

**Pull request merged**
