### PR TITLE
fix(HMS-4016): Include iqe-idm-plugin tests in podengo PR checks

### PR DESCRIPTION
**Pull request by aadhikar**

### CODE REVIEW

**Comment by aadhikar** [comment]
@app-sre-bot /retest

**Comment by avisiedo** [comment]
Current message at https://github.com/podengo-project/idmsvc-backend/actions/runs/9285515393/job/25550191591?pr=212 is a flaky unit test; See HMS-3803

/retest

**Review by mshriver — APPROVED** [review]

**Pull request merged**
