### PR TITLE
feat(HMS-3968): add service account support

### PR DESCRIPTION
**Pull request by avisiedo**
This change add the support for the service accounts,
so the platform can use it for automation.

TODO:

- [x] Bump platform-go-middleware `v2`: https://github.com/podengo-project/idmsvc-backend/pull/234
- [x] Enforce Service accounts predicate: https://github.com/podengo-project/idmsvc-backend/pull/235
    - [x] Add additional unit tests to cover the new enforce predicate.
- [x] Update change to semantic `AsUser` `AsSystem` `AsServiceAccount` to the base suite test. Credits on @pvoborni : https://github.com/podengo-project/idmsvc-backend/pull/232
    - [x] split the refactor of the new semantic and the specific changes for service account.
- [x] Update integration tests to check Service Accounts as it is made currently with the users: https://github.com/podengo-project/idmsvc-backend/pull/233
- [x] Reorg the commits.
- [x] Update helper scripts at `./test/scripts/` to allow leverage service accounts: https://github.com/podengo-project/idmsvc-backend/pull/236
    - [x] Update dev documentation: https://github.com/podengo-project/idmsvc-backend/pull/244
- [x] Update helper scripts at `./scripts/http/*.http` to allow leverage service accounts. (new PR): https://github.com/podengo-project/idmsvc-backend/pull/237

Related PR merged (order matter):
- [x] https://github.com/podengo-project/idmsvc-backend/pull/234
- [x] https://github.com/podengo-project/idmsvc-backend/pull/235
- [x] https://github.com/podengo-project/idmsvc-backend/pull/232
- [x] https://github.com/podengo-project/idmsvc-backend/pull/233
- [x] https://github.com/podengo-project/idmsvc-backend/pull/236
- [x] https://github.com/podengo-project/idmsvc-backend/pull/244
- [x] https://github.com/podengo-project/idmsvc-backend/pull/237
- [x] https://github.com/podengo-project/idmsvc-backend/pull/249 ???

### CODE REVIEW

**Comment by frasertweedale** [comment]
For sure, let's deal with this as 3 PRs:

1. `bump: github.com/redhatinsights/platform-go-middlewares/v2 v2.0.0-beta.2`
2. the service account stuff
3. The big `refactor(HMS-3968): add As(XRHID...) semantics`

**Comment by avisiedo** [comment]
I have reorged the commits before go on.
- Bump new library: The first 3 commits build and pass the tests, so they can be moved in a different PR. https://github.com/podengo-project/idmsvc-backend/pull/228 could point to the commit dfab7592c6f98713d01bceb14b0e68a7a88ed6b8 and the tests should run.
- Add Service Account: I have gathered the current commits, but I need to add more unit tests to coverage, this second PR is not ready yet. In progress.
- Refactor to add `As` semantic: it is gathered the changes, but as it is the last, I don't want to propose.

**Comment by avisiedo** [comment]
I have updated a little the description of the PR, and reordered as the PR trial would happen, so this PR provide a big picture and link to the smaller one.

**Comment by avisiedo** [comment]
All the related PR that implement the whole HMS-3968 ticket now are landed; closing this PR as this changes have been divided in smaller PRs and the propose of tracking is not necessary now.

**Pull request closed without merging**
