### PR TITLE
build(HMS-4078): bump golang1.21and libraries

### PR DESCRIPTION
**Pull request by avisiedo**
- Update golang dependencies to use go1.21
- Update base container to use go1.21
- Update make to use go1.21
- Update pipeline to use go1.21

### CODE REVIEW

**Comment by avisiedo** [comment]
Checking by:

```sh
$ go clean -modcache -cache
$ rm -rf tools/bin
$ make tidy install-tools
$ make clean build container-build
```

And relaunching the pipeline on github.

**Review by pvoborni — COMMENTED** [review]
Mostly LGTM, but have a Q. I see 3 other usages of go 1.20 in the code base:

```
.gitlab-ci.yml:image: golang:1.20
.golangci.yaml:    lang-version: "1.20"
README.md:- golang 1.20 (not `gcc-go`)
```

I think we can ignore the `.gitlab-ci`, but what about the `.golangci.yaml` and `README`?

**Comment by avisiedo** [comment]
:+1: thanks I didn't realize about them

**Review by pvoborni — APPROVED** [review]
LGTM

**Pull request merged**
