### PR TITLE
HMS-2590 fix: use 'resources' tag for PATCH /domains/:domain_id

### PR DESCRIPTION
**Pull request by avisiedo**
Update the generated spec.gen.go file after the new API has been attached.

### CODE REVIEW

**Comment by tiran** [comment]
Could you please change the commit message and PR to reflect the details of the change, while focusing on relevant changes? The fact only that `spec.gen.go` has changed, is not interesting. As a reviewer and developer, I'm interested to know what has in the file.

Also use upper-case letters for title reference

```
HMS-2590 fix: Regenerate OpenAPI for PATCH /domains/:domain_id

Update to latest OpenAPI spec. `PATCH /domains/:domain_id` now has `resources` tag instead of `actions` tag.
```

**Comment by avisiedo** [comment]
@tiran thanks mate! updated!

**Comment by tiran** [comment]
You updated the ticket description, but not the commit message that will land in git. The commit message is IMHO more important than the ticket description. After all the information ends up in the commit history.

A sentence or two is more than sufficient for a trivial change. The change doesn't even affect the backend.

**Comment by avisiedo** [comment]
@tiran  thanks mate! I didn't realize about the commit message; now it is updated.

**Comment by tiran** [comment]
I hate do be pedantic ... but you didn't read my last comment, did you? :) Now the commit message is overly long and goes into unimportant details.

In my opinion and experience, commit messages should provide a short overview of the "what" and "why" of the change set. They should be as long as necessary and as short as possible. For this PR, one sentence, maybe two are more than sufficient. Personally I would not even include an explanation, because the change does not have an impact on the behavior of the backend. It only updates the serialized JSON string of the schema.

**Comment by avisiedo** [comment]
> I hate do be pedantic ... but you didn't read my last comment, did you? :) Now the commit message is overly long and goes into unimportant details.
> 
> In my opinion and experience, commit messages should provide a short overview of the "what" and "why" of the change set. They should be as long as necessary and as short as possible. For this PR, one sentence, maybe two are more than sufficient. Personally I would not even include an explanation, because the change does not have an impact on the behavior of the backend. It only updates the serialized JSON string of the schema.

thanks mate! at the beginning I understood it was the PR message; later I updated the commit message; I have updated with a short description. :+1:

**Review by frasertweedale — APPROVED** [review]

**Pull request merged**
